name: dev-stack
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker-config/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:5432
  pgadmin:
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=myemail@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=a12345678
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    volumes:
      - ./docker-config/servers_pgadmin.json:/pgadmin4/servers.json

volumes:
  postgres_volume:
    name: postgres_test_adonisv6
